// Code generated by protoc-gen-gogo.
// source: safari.proto
// DO NOT EDIT!

package pbf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"

import strconv "strconv"

import strings "strings"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
import sort "sort"
import reflect "reflect"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Region_Code int32

const (
	KANTO  Region_Code = 0
	JOHTO  Region_Code = 1
	HOENN  Region_Code = 2
	SINNOH Region_Code = 3
	UNOVA  Region_Code = 4
	KALOS  Region_Code = 5
	ALOLA  Region_Code = 6
)

var Region_Code_name = map[int32]string{
	0: "KANTO",
	1: "JOHTO",
	2: "HOENN",
	3: "SINNOH",
	4: "UNOVA",
	5: "KALOS",
	6: "ALOLA",
}
var Region_Code_value = map[string]int32{
	"KANTO":  0,
	"JOHTO":  1,
	"HOENN":  2,
	"SINNOH": 3,
	"UNOVA":  4,
	"KALOS":  5,
	"ALOLA":  6,
}

func (Region_Code) EnumDescriptor() ([]byte, []int) { return fileDescriptorSafari, []int{1, 0} }

type Event struct {
	Trainer *Trainer   `protobuf:"bytes,1,opt,name=trainer" json:"trainer,omitempty"`
	Pokemon *Pokemon   `protobuf:"bytes,2,opt,name=pokemon" json:"pokemon,omitempty"`
	Region  *Region    `protobuf:"bytes,3,opt,name=region" json:"region,omitempty"`
	Time    *Timestamp `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptorSafari, []int{0} }

func (m *Event) GetTrainer() *Trainer {
	if m != nil {
		return m.Trainer
	}
	return nil
}

func (m *Event) GetPokemon() *Pokemon {
	if m != nil {
		return m.Pokemon
	}
	return nil
}

func (m *Event) GetRegion() *Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *Event) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Region struct {
	Code    Region_Code `protobuf:"varint,1,opt,name=code,proto3,enum=buckhx.pokedex.Region_Code" json:"code,omitempty"`
	OptCode int32       `protobuf:"varint,15,opt,name=opt_code,json=optCode,proto3" json:"opt_code,omitempty"`
}

func (m *Region) Reset()                    { *m = Region{} }
func (*Region) ProtoMessage()               {}
func (*Region) Descriptor() ([]byte, []int) { return fileDescriptorSafari, []int{1} }

func init() {
	proto.RegisterType((*Event)(nil), "buckhx.pokedex.Event")
	proto.RegisterType((*Region)(nil), "buckhx.pokedex.Region")
	proto.RegisterEnum("buckhx.pokedex.Region_Code", Region_Code_name, Region_Code_value)
}
func (x Region_Code) String() string {
	s, ok := Region_Code_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Event) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Event)
	if !ok {
		that2, ok := that.(Event)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Trainer.Equal(that1.Trainer) {
		return false
	}
	if !this.Pokemon.Equal(that1.Pokemon) {
		return false
	}
	if !this.Region.Equal(that1.Region) {
		return false
	}
	if !this.Time.Equal(that1.Time) {
		return false
	}
	return true
}
func (this *Region) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Region)
	if !ok {
		that2, ok := that.(Region)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.OptCode != that1.OptCode {
		return false
	}
	return true
}
func (this *Event) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&pbf.Event{")
	if this.Trainer != nil {
		s = append(s, "Trainer: "+fmt.Sprintf("%#v", this.Trainer)+",\n")
	}
	if this.Pokemon != nil {
		s = append(s, "Pokemon: "+fmt.Sprintf("%#v", this.Pokemon)+",\n")
	}
	if this.Region != nil {
		s = append(s, "Region: "+fmt.Sprintf("%#v", this.Region)+",\n")
	}
	if this.Time != nil {
		s = append(s, "Time: "+fmt.Sprintf("%#v", this.Time)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Region) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pbf.Region{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "OptCode: "+fmt.Sprintf("%#v", this.OptCode)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSafari(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringSafari(e map[int32]github_com_gogo_protobuf_proto.Extension) string {
	if e == nil {
		return "nil"
	}
	s := "map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "}"
	return s
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Safari service

type SafariClient interface {
	// Encounter might add a pokemon to the event
	//
	// A pokemon will be added to the event and timestmap set if one is encountered
	Encounter(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	// Catch will attempt to catch the pokemon
	//
	// If caught, this pokemon will be deposited into the Trainer's PC
	Catch(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error)
}

type safariClient struct {
	cc *grpc.ClientConn
}

func NewSafariClient(cc *grpc.ClientConn) SafariClient {
	return &safariClient{cc}
}

func (c *safariClient) Encounter(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/buckhx.pokedex.Safari/Encounter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safariClient) Catch(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/buckhx.pokedex.Safari/Catch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Safari service

type SafariServer interface {
	// Encounter might add a pokemon to the event
	//
	// A pokemon will be added to the event and timestmap set if one is encountered
	Encounter(context.Context, *Event) (*Event, error)
	// Catch will attempt to catch the pokemon
	//
	// If caught, this pokemon will be deposited into the Trainer's PC
	Catch(context.Context, *Event) (*Response, error)
}

func RegisterSafariServer(s *grpc.Server, srv SafariServer) {
	s.RegisterService(&_Safari_serviceDesc, srv)
}

func _Safari_Encounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafariServer).Encounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buckhx.pokedex.Safari/Encounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafariServer).Encounter(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safari_Catch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafariServer).Catch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buckhx.pokedex.Safari/Catch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafariServer).Catch(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _Safari_serviceDesc = grpc.ServiceDesc{
	ServiceName: "buckhx.pokedex.Safari",
	HandlerType: (*SafariServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encounter",
			Handler:    _Safari_Encounter_Handler,
		},
		{
			MethodName: "Catch",
			Handler:    _Safari_Catch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptorSafari,
}

func (m *Event) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Event) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Trainer != nil {
		data[i] = 0xa
		i++
		i = encodeVarintSafari(data, i, uint64(m.Trainer.Size()))
		n1, err := m.Trainer.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Pokemon != nil {
		data[i] = 0x12
		i++
		i = encodeVarintSafari(data, i, uint64(m.Pokemon.Size()))
		n2, err := m.Pokemon.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Region != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintSafari(data, i, uint64(m.Region.Size()))
		n3, err := m.Region.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Time != nil {
		data[i] = 0x22
		i++
		i = encodeVarintSafari(data, i, uint64(m.Time.Size()))
		n4, err := m.Time.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func (m *Region) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Region) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintSafari(data, i, uint64(m.Code))
	}
	if m.OptCode != 0 {
		data[i] = 0x78
		i++
		i = encodeVarintSafari(data, i, uint64(m.OptCode))
	}
	return i, nil
}

func encodeFixed64Safari(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Safari(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintSafari(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *Event) Size() (n int) {
	var l int
	_ = l
	if m.Trainer != nil {
		l = m.Trainer.Size()
		n += 1 + l + sovSafari(uint64(l))
	}
	if m.Pokemon != nil {
		l = m.Pokemon.Size()
		n += 1 + l + sovSafari(uint64(l))
	}
	if m.Region != nil {
		l = m.Region.Size()
		n += 1 + l + sovSafari(uint64(l))
	}
	if m.Time != nil {
		l = m.Time.Size()
		n += 1 + l + sovSafari(uint64(l))
	}
	return n
}

func (m *Region) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovSafari(uint64(m.Code))
	}
	if m.OptCode != 0 {
		n += 1 + sovSafari(uint64(m.OptCode))
	}
	return n
}

func sovSafari(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSafari(x uint64) (n int) {
	return sovSafari(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Event) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Event{`,
		`Trainer:` + strings.Replace(fmt.Sprintf("%v", this.Trainer), "Trainer", "Trainer", 1) + `,`,
		`Pokemon:` + strings.Replace(fmt.Sprintf("%v", this.Pokemon), "Pokemon", "Pokemon", 1) + `,`,
		`Region:` + strings.Replace(fmt.Sprintf("%v", this.Region), "Region", "Region", 1) + `,`,
		`Time:` + strings.Replace(fmt.Sprintf("%v", this.Time), "Timestamp", "Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Region) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Region{`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`OptCode:` + fmt.Sprintf("%v", this.OptCode) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringSafari(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Event) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSafari
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trainer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSafari
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trainer == nil {
				m.Trainer = &Trainer{}
			}
			if err := m.Trainer.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pokemon", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSafari
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pokemon == nil {
				m.Pokemon = &Pokemon{}
			}
			if err := m.Pokemon.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSafari
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Region == nil {
				m.Region = &Region{}
			}
			if err := m.Region.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSafari
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Time == nil {
				m.Time = &Timestamp{}
			}
			if err := m.Time.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSafari(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSafari
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Region) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSafari
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Region: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Region: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Code |= (Region_Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptCode", wireType)
			}
			m.OptCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.OptCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSafari(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSafari
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSafari(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSafari
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSafari
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSafari
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSafari
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSafari(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSafari = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSafari   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorSafari = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xda, 0x24, 0x63, 0x06, 0x4a, 0x64, 0x09, 0xe8, 0x0a, 0xaa, 0x50, 0x4e, 0x1c, 0xc0,
	0x56, 0x0b, 0x12, 0xe7, 0x32, 0x55, 0x2a, 0x30, 0x25, 0x28, 0x2d, 0x1c, 0xb8, 0x20, 0x37, 0xf5,
	0xba, 0x68, 0xd4, 0x8e, 0x12, 0x17, 0x0d, 0x55, 0x93, 0x10, 0xbf, 0x00, 0x89, 0x3f, 0x81, 0xf8,
	0x25, 0x1c, 0x38, 0x4c, 0xe2, 0xc2, 0x91, 0x0d, 0x0e, 0x1c, 0x38, 0xf0, 0x13, 0x78, 0xb6, 0xd3,
	0xc3, 0xb6, 0xee, 0xf0, 0xe4, 0xcf, 0xef, 0xfb, 0xbe, 0xbc, 0x97, 0xf7, 0x8c, 0xae, 0x94, 0x6c,
	0x97, 0x15, 0x19, 0xc9, 0x0b, 0xa9, 0x24, 0x6e, 0x4e, 0x16, 0xe9, 0xfe, 0xde, 0x01, 0xc9, 0xe5,
	0x3e, 0x9f, 0xf2, 0x83, 0xf6, 0xed, 0x99, 0x94, 0xb3, 0x37, 0x9c, 0xb2, 0x3c, 0xa3, 0x4c, 0x08,
	0xa9, 0x98, 0xca, 0xa4, 0x28, 0xad, 0xba, 0x7d, 0xb5, 0x92, 0x55, 0xd7, 0x66, 0xc1, 0x67, 0x59,
	0xa9, 0x8a, 0x77, 0xf6, 0x1e, 0x7e, 0x73, 0x90, 0x37, 0x78, 0xcb, 0x85, 0xc2, 0x5d, 0xb4, 0xa1,
	0x0a, 0x96, 0x09, 0x5e, 0xb4, 0x9c, 0x3b, 0xce, 0xdd, 0xcb, 0xbd, 0x9b, 0xe4, 0x74, 0x21, 0x32,
	0xb6, 0x74, 0xb2, 0xd2, 0x69, 0x8b, 0xe6, 0xe6, 0x52, 0xb4, 0xea, 0xeb, 0x2d, 0xcf, 0x2d, 0x9d,
	0xac, 0x74, 0x98, 0x20, 0x5f, 0x77, 0x00, 0x8e, 0x86, 0x71, 0xdc, 0x38, 0xeb, 0x48, 0x0c, 0x9b,
	0x54, 0x2a, 0x7c, 0x1f, 0xb9, 0x2a, 0x9b, 0xf3, 0x96, 0x6b, 0xd4, 0x5b, 0xe7, 0x5a, 0x02, 0xae,
	0x54, 0x6c, 0x9e, 0x27, 0x46, 0x16, 0x7e, 0x71, 0x90, 0x6f, 0xbf, 0x80, 0x29, 0x72, 0x53, 0x39,
	0xe5, 0xe6, 0x67, 0x9a, 0xbd, 0x5b, 0xeb, 0xeb, 0x90, 0x6d, 0x90, 0x24, 0x46, 0x88, 0xb7, 0xd0,
	0x25, 0x99, 0xab, 0xd7, 0xc6, 0x74, 0x0d, 0x4c, 0x5e, 0xb2, 0x01, 0x77, 0x2d, 0x08, 0xc7, 0xc8,
	0xd5, 0x27, 0xde, 0x44, 0xde, 0xb3, 0x7e, 0x34, 0x8e, 0x83, 0x9a, 0x86, 0x4f, 0xe3, 0x21, 0x40,
	0x47, 0xc3, 0x61, 0x3c, 0x88, 0xa2, 0xa0, 0x8e, 0x11, 0xf2, 0x47, 0x4f, 0xa2, 0x28, 0x1e, 0x06,
	0x0d, 0x9d, 0x7e, 0x11, 0xc5, 0x2f, 0xfb, 0x81, 0x6b, 0x7d, 0x3b, 0xf1, 0x28, 0xf0, 0x34, 0x04,
	0xb4, 0xd3, 0x0f, 0xfc, 0xde, 0x5f, 0x68, 0x76, 0x64, 0x36, 0x8b, 0x0b, 0xb4, 0x39, 0x10, 0xa9,
	0x5c, 0x08, 0x05, 0x63, 0xbd, 0x7e, 0xb6, 0x57, 0xb3, 0xa0, 0xf6, 0xfa, 0x74, 0xf8, 0xe8, 0xc3,
	0xf7, 0xdf, 0x9f, 0xea, 0x5d, 0x4c, 0x69, 0xb5, 0x16, 0xba, 0xac, 0x00, 0x59, 0x64, 0xd3, 0x43,
	0x6a, 0x07, 0x49, 0x97, 0xf6, 0x24, 0xab, 0x5f, 0x3c, 0xc4, 0x02, 0x79, 0xdb, 0x4c, 0xa5, 0x7b,
	0x17, 0xd5, 0x6b, 0x9d, 0x1f, 0x59, 0x99, 0xc3, 0xc3, 0xe2, 0xe1, 0x43, 0x53, 0x92, 0x84, 0xf7,
	0x2e, 0x28, 0x59, 0x2d, 0x9b, 0x2e, 0x2b, 0x60, 0xb2, 0x8f, 0xbb, 0x47, 0xc7, 0x9d, 0xda, 0x0f,
	0x88, 0x7f, 0xc7, 0x1d, 0xe7, 0xfd, 0x49, 0xc7, 0xf9, 0x0c, 0xf1, 0x15, 0xe2, 0x08, 0xe2, 0x27,
	0xc4, 0x9f, 0x13, 0xe0, 0xe0, 0xfc, 0xf8, 0xab, 0x53, 0x7b, 0xd5, 0xc8, 0x27, 0xbb, 0x13, 0xdf,
	0x3c, 0xd2, 0x07, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xa3, 0xe8, 0x56, 0x01, 0x03, 0x00,
	0x00,
}
