// Code generated by protoc-gen-gogo.
// source: warden.proto
// DO NOT EDIT!

package pbf

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import strconv "strconv"

import strings "strings"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
import sort "sort"
import reflect "reflect"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BattleMessage_Status int32

const (
	OK    BattleMessage_Status = 0
	DONE  BattleMessage_Status = 1
	ERROR BattleMessage_Status = 2
)

var BattleMessage_Status_name = map[int32]string{
	0: "OK",
	1: "DONE",
	2: "ERROR",
}
var BattleMessage_Status_value = map[string]int32{
	"OK":    0,
	"DONE":  1,
	"ERROR": 2,
}

func (BattleMessage_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptorWarden, []int{2, 0} }

type Zone_Code int32

const (
	KANTO  Zone_Code = 0
	JOHTO  Zone_Code = 1
	HOENN  Zone_Code = 2
	SINNOH Zone_Code = 3
	UNOVA  Zone_Code = 4
	KALOS  Zone_Code = 5
	ALOLA  Zone_Code = 6
)

var Zone_Code_name = map[int32]string{
	0: "KANTO",
	1: "JOHTO",
	2: "HOENN",
	3: "SINNOH",
	4: "UNOVA",
	5: "KALOS",
	6: "ALOLA",
}
var Zone_Code_value = map[string]int32{
	"KANTO":  0,
	"JOHTO":  1,
	"HOENN":  2,
	"SINNOH": 3,
	"UNOVA":  4,
	"KALOS":  5,
	"ALOLA":  6,
}

func (Zone_Code) EnumDescriptor() ([]byte, []int) { return fileDescriptorWarden, []int{3, 0} }

type Ticket struct {
	Uid     string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Trainer *Trainer       `protobuf:"bytes,2,opt,name=trainer" json:"trainer,omitempty"`
	Zone    *Zone          `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
	Time    *Timestamp     `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	Expires *Ticket_Expiry `protobuf:"bytes,5,opt,name=expires" json:"expires,omitempty"`
}

func (m *Ticket) Reset()                    { *m = Ticket{} }
func (*Ticket) ProtoMessage()               {}
func (*Ticket) Descriptor() ([]byte, []int) { return fileDescriptorWarden, []int{0} }

func (m *Ticket) GetTrainer() *Trainer {
	if m != nil {
		return m.Trainer
	}
	return nil
}

func (m *Ticket) GetZone() *Zone {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *Ticket) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Ticket) GetExpires() *Ticket_Expiry {
	if m != nil {
		return m.Expires
	}
	return nil
}

type Ticket_Expiry struct {
	Encounters int32 `protobuf:"varint,1,opt,name=encounters,proto3" json:"encounters,omitempty"`
	Time       int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *Ticket_Expiry) Reset()                    { *m = Ticket_Expiry{} }
func (*Ticket_Expiry) ProtoMessage()               {}
func (*Ticket_Expiry) Descriptor() ([]byte, []int) { return fileDescriptorWarden, []int{0, 0} }

type Action struct {
	// Types that are valid to be assigned to Move:
	//	*Action_Attack
	//	*Action_Item
	//	*Action_Switch
	//	*Action_Run
	Move isAction_Move `protobuf_oneof:"move"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptorWarden, []int{1} }

type isAction_Move interface {
	isAction_Move()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type Action_Attack struct {
	Attack string `protobuf:"bytes,1,opt,name=attack,proto3,oneof"`
}
type Action_Item struct {
	Item string `protobuf:"bytes,2,opt,name=item,proto3,oneof"`
}
type Action_Switch struct {
	Switch *Pokemon `protobuf:"bytes,3,opt,name=switch,oneof"`
}
type Action_Run struct {
	Run bool `protobuf:"varint,4,opt,name=run,proto3,oneof"`
}

func (*Action_Attack) isAction_Move() {}
func (*Action_Item) isAction_Move()   {}
func (*Action_Switch) isAction_Move() {}
func (*Action_Run) isAction_Move()    {}

func (m *Action) GetMove() isAction_Move {
	if m != nil {
		return m.Move
	}
	return nil
}

func (m *Action) GetAttack() string {
	if x, ok := m.GetMove().(*Action_Attack); ok {
		return x.Attack
	}
	return ""
}

func (m *Action) GetItem() string {
	if x, ok := m.GetMove().(*Action_Item); ok {
		return x.Item
	}
	return ""
}

func (m *Action) GetSwitch() *Pokemon {
	if x, ok := m.GetMove().(*Action_Switch); ok {
		return x.Switch
	}
	return nil
}

func (m *Action) GetRun() bool {
	if x, ok := m.GetMove().(*Action_Run); ok {
		return x.Run
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Action) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Action_OneofMarshaler, _Action_OneofUnmarshaler, _Action_OneofSizer, []interface{}{
		(*Action_Attack)(nil),
		(*Action_Item)(nil),
		(*Action_Switch)(nil),
		(*Action_Run)(nil),
	}
}

func _Action_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Action)
	// move
	switch x := m.Move.(type) {
	case *Action_Attack:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Attack)
	case *Action_Item:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Item)
	case *Action_Switch:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Switch); err != nil {
			return err
		}
	case *Action_Run:
		t := uint64(0)
		if x.Run {
			t = 1
		}
		_ = b.EncodeVarint(4<<3 | proto.WireVarint)
		_ = b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("Action.Move has unexpected type %T", x)
	}
	return nil
}

func _Action_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Action)
	switch tag {
	case 1: // move.attack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Move = &Action_Attack{x}
		return true, err
	case 2: // move.item
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Move = &Action_Item{x}
		return true, err
	case 3: // move.switch
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Pokemon)
		err := b.DecodeMessage(msg)
		m.Move = &Action_Switch{msg}
		return true, err
	case 4: // move.run
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Move = &Action_Run{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _Action_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Action)
	// move
	switch x := m.Move.(type) {
	case *Action_Attack:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Attack)))
		n += len(x.Attack)
	case *Action_Item:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Item)))
		n += len(x.Item)
	case *Action_Switch:
		s := proto.Size(x.Switch)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Action_Run:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type BattleMessage struct {
	Msg    string               `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Status BattleMessage_Status `protobuf:"varint,2,opt,name=status,proto3,enum=buckhx.safari.warden.BattleMessage_Status" json:"status,omitempty"`
}

func (m *BattleMessage) Reset()                    { *m = BattleMessage{} }
func (*BattleMessage) ProtoMessage()               {}
func (*BattleMessage) Descriptor() ([]byte, []int) { return fileDescriptorWarden, []int{2} }

type Zone struct {
	Region  Zone_Code `protobuf:"varint,1,opt,name=region,proto3,enum=buckhx.safari.warden.Zone_Code" json:"region,omitempty"`
	OptCode int32     `protobuf:"varint,15,opt,name=opt_code,json=optCode,proto3" json:"opt_code,omitempty"`
}

func (m *Zone) Reset()                    { *m = Zone{} }
func (*Zone) ProtoMessage()               {}
func (*Zone) Descriptor() ([]byte, []int) { return fileDescriptorWarden, []int{3} }

func init() {
	proto.RegisterType((*Ticket)(nil), "buckhx.safari.warden.Ticket")
	proto.RegisterType((*Ticket_Expiry)(nil), "buckhx.safari.warden.Ticket.Expiry")
	proto.RegisterType((*Action)(nil), "buckhx.safari.warden.Action")
	proto.RegisterType((*BattleMessage)(nil), "buckhx.safari.warden.BattleMessage")
	proto.RegisterType((*Zone)(nil), "buckhx.safari.warden.Zone")
	proto.RegisterEnum("buckhx.safari.warden.BattleMessage_Status", BattleMessage_Status_name, BattleMessage_Status_value)
	proto.RegisterEnum("buckhx.safari.warden.Zone_Code", Zone_Code_name, Zone_Code_value)
}
func (x BattleMessage_Status) String() string {
	s, ok := BattleMessage_Status_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x Zone_Code) String() string {
	s, ok := Zone_Code_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Ticket) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Ticket)
	if !ok {
		that2, ok := that.(Ticket)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Uid != that1.Uid {
		return false
	}
	if !this.Trainer.Equal(that1.Trainer) {
		return false
	}
	if !this.Zone.Equal(that1.Zone) {
		return false
	}
	if !this.Time.Equal(that1.Time) {
		return false
	}
	if !this.Expires.Equal(that1.Expires) {
		return false
	}
	return true
}
func (this *Ticket_Expiry) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Ticket_Expiry)
	if !ok {
		that2, ok := that.(Ticket_Expiry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Encounters != that1.Encounters {
		return false
	}
	if this.Time != that1.Time {
		return false
	}
	return true
}
func (this *Action) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Action)
	if !ok {
		that2, ok := that.(Action)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if that1.Move == nil {
		if this.Move != nil {
			return false
		}
	} else if this.Move == nil {
		return false
	} else if !this.Move.Equal(that1.Move) {
		return false
	}
	return true
}
func (this *Action_Attack) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Action_Attack)
	if !ok {
		that2, ok := that.(Action_Attack)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Attack != that1.Attack {
		return false
	}
	return true
}
func (this *Action_Item) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Action_Item)
	if !ok {
		that2, ok := that.(Action_Item)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Item != that1.Item {
		return false
	}
	return true
}
func (this *Action_Switch) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Action_Switch)
	if !ok {
		that2, ok := that.(Action_Switch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Switch.Equal(that1.Switch) {
		return false
	}
	return true
}
func (this *Action_Run) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Action_Run)
	if !ok {
		that2, ok := that.(Action_Run)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Run != that1.Run {
		return false
	}
	return true
}
func (this *BattleMessage) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BattleMessage)
	if !ok {
		that2, ok := that.(BattleMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Msg != that1.Msg {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	return true
}
func (this *Zone) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Zone)
	if !ok {
		that2, ok := that.(Zone)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Region != that1.Region {
		return false
	}
	if this.OptCode != that1.OptCode {
		return false
	}
	return true
}
func (this *Ticket) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&pbf.Ticket{")
	s = append(s, "Uid: "+fmt.Sprintf("%#v", this.Uid)+",\n")
	if this.Trainer != nil {
		s = append(s, "Trainer: "+fmt.Sprintf("%#v", this.Trainer)+",\n")
	}
	if this.Zone != nil {
		s = append(s, "Zone: "+fmt.Sprintf("%#v", this.Zone)+",\n")
	}
	if this.Time != nil {
		s = append(s, "Time: "+fmt.Sprintf("%#v", this.Time)+",\n")
	}
	if this.Expires != nil {
		s = append(s, "Expires: "+fmt.Sprintf("%#v", this.Expires)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Ticket_Expiry) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pbf.Ticket_Expiry{")
	s = append(s, "Encounters: "+fmt.Sprintf("%#v", this.Encounters)+",\n")
	s = append(s, "Time: "+fmt.Sprintf("%#v", this.Time)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Action) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&pbf.Action{")
	if this.Move != nil {
		s = append(s, "Move: "+fmt.Sprintf("%#v", this.Move)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Action_Attack) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&pbf.Action_Attack{` +
		`Attack:` + fmt.Sprintf("%#v", this.Attack) + `}`}, ", ")
	return s
}
func (this *Action_Item) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&pbf.Action_Item{` +
		`Item:` + fmt.Sprintf("%#v", this.Item) + `}`}, ", ")
	return s
}
func (this *Action_Switch) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&pbf.Action_Switch{` +
		`Switch:` + fmt.Sprintf("%#v", this.Switch) + `}`}, ", ")
	return s
}
func (this *Action_Run) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&pbf.Action_Run{` +
		`Run:` + fmt.Sprintf("%#v", this.Run) + `}`}, ", ")
	return s
}
func (this *BattleMessage) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pbf.BattleMessage{")
	s = append(s, "Msg: "+fmt.Sprintf("%#v", this.Msg)+",\n")
	s = append(s, "Status: "+fmt.Sprintf("%#v", this.Status)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Zone) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pbf.Zone{")
	s = append(s, "Region: "+fmt.Sprintf("%#v", this.Region)+",\n")
	s = append(s, "OptCode: "+fmt.Sprintf("%#v", this.OptCode)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringWarden(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringWarden(m github_com_gogo_protobuf_proto.Message) string {
	e := github_com_gogo_protobuf_proto.GetUnsafeExtensionsMap(m)
	if e == nil {
		return "nil"
	}
	s := "proto.NewUnsafeXXX_InternalExtensions(map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "})"
	return s
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Warden service

type WardenClient interface {
	// Encounter might add a pokemon to the event
	//
	// A pokemon will be added to the event and timestmap set if one is encountered
	Enter(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*Ticket, error)
	// Catch will attempt to catch the pokemon
	//
	// If caught, this pokemon will be deposited into the Trainer's PC
	Encounter(ctx context.Context, opts ...grpc.CallOption) (Warden_EncounterClient, error)
}

type wardenClient struct {
	cc *grpc.ClientConn
}

func NewWardenClient(cc *grpc.ClientConn) WardenClient {
	return &wardenClient{cc}
}

func (c *wardenClient) Enter(ctx context.Context, in *Ticket, opts ...grpc.CallOption) (*Ticket, error) {
	out := new(Ticket)
	err := grpc.Invoke(ctx, "/buckhx.safari.warden.Warden/Enter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wardenClient) Encounter(ctx context.Context, opts ...grpc.CallOption) (Warden_EncounterClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Warden_serviceDesc.Streams[0], c.cc, "/buckhx.safari.warden.Warden/Encounter", opts...)
	if err != nil {
		return nil, err
	}
	x := &wardenEncounterClient{stream}
	return x, nil
}

type Warden_EncounterClient interface {
	Send(*Action) error
	Recv() (*BattleMessage, error)
	grpc.ClientStream
}

type wardenEncounterClient struct {
	grpc.ClientStream
}

func (x *wardenEncounterClient) Send(m *Action) error {
	return x.ClientStream.SendMsg(m)
}

func (x *wardenEncounterClient) Recv() (*BattleMessage, error) {
	m := new(BattleMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Warden service

type WardenServer interface {
	// Encounter might add a pokemon to the event
	//
	// A pokemon will be added to the event and timestmap set if one is encountered
	Enter(context.Context, *Ticket) (*Ticket, error)
	// Catch will attempt to catch the pokemon
	//
	// If caught, this pokemon will be deposited into the Trainer's PC
	Encounter(Warden_EncounterServer) error
}

func RegisterWardenServer(s *grpc.Server, srv WardenServer) {
	s.RegisterService(&_Warden_serviceDesc, srv)
}

func _Warden_Enter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ticket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WardenServer).Enter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buckhx.safari.warden.Warden/Enter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WardenServer).Enter(ctx, req.(*Ticket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Warden_Encounter_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WardenServer).Encounter(&wardenEncounterServer{stream})
}

type Warden_EncounterServer interface {
	Send(*BattleMessage) error
	Recv() (*Action, error)
	grpc.ServerStream
}

type wardenEncounterServer struct {
	grpc.ServerStream
}

func (x *wardenEncounterServer) Send(m *BattleMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *wardenEncounterServer) Recv() (*Action, error) {
	m := new(Action)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Warden_serviceDesc = grpc.ServiceDesc{
	ServiceName: "buckhx.safari.warden.Warden",
	HandlerType: (*WardenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enter",
			Handler:    _Warden_Enter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Encounter",
			Handler:       _Warden_Encounter_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptorWarden,
}

func (m *Ticket) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Ticket) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintWarden(data, i, uint64(len(m.Uid)))
		i += copy(data[i:], m.Uid)
	}
	if m.Trainer != nil {
		data[i] = 0x12
		i++
		i = encodeVarintWarden(data, i, uint64(m.Trainer.Size()))
		n1, err := m.Trainer.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Zone != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintWarden(data, i, uint64(m.Zone.Size()))
		n2, err := m.Zone.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Time != nil {
		data[i] = 0x22
		i++
		i = encodeVarintWarden(data, i, uint64(m.Time.Size()))
		n3, err := m.Time.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Expires != nil {
		data[i] = 0x2a
		i++
		i = encodeVarintWarden(data, i, uint64(m.Expires.Size()))
		n4, err := m.Expires.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func (m *Ticket_Expiry) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Ticket_Expiry) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Encounters != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintWarden(data, i, uint64(m.Encounters))
	}
	if m.Time != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintWarden(data, i, uint64(m.Time))
	}
	return i, nil
}

func (m *Action) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Action) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Move != nil {
		nn5, err := m.Move.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += nn5
	}
	return i, nil
}

func (m *Action_Attack) MarshalTo(data []byte) (int, error) {
	i := 0
	data[i] = 0xa
	i++
	i = encodeVarintWarden(data, i, uint64(len(m.Attack)))
	i += copy(data[i:], m.Attack)
	return i, nil
}
func (m *Action_Item) MarshalTo(data []byte) (int, error) {
	i := 0
	data[i] = 0x12
	i++
	i = encodeVarintWarden(data, i, uint64(len(m.Item)))
	i += copy(data[i:], m.Item)
	return i, nil
}
func (m *Action_Switch) MarshalTo(data []byte) (int, error) {
	i := 0
	if m.Switch != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintWarden(data, i, uint64(m.Switch.Size()))
		n6, err := m.Switch.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}
func (m *Action_Run) MarshalTo(data []byte) (int, error) {
	i := 0
	data[i] = 0x20
	i++
	if m.Run {
		data[i] = 1
	} else {
		data[i] = 0
	}
	i++
	return i, nil
}
func (m *BattleMessage) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *BattleMessage) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Msg) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintWarden(data, i, uint64(len(m.Msg)))
		i += copy(data[i:], m.Msg)
	}
	if m.Status != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintWarden(data, i, uint64(m.Status))
	}
	return i, nil
}

func (m *Zone) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Zone) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Region != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintWarden(data, i, uint64(m.Region))
	}
	if m.OptCode != 0 {
		data[i] = 0x78
		i++
		i = encodeVarintWarden(data, i, uint64(m.OptCode))
	}
	return i, nil
}

func encodeFixed64Warden(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Warden(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintWarden(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *Ticket) Size() (n int) {
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovWarden(uint64(l))
	}
	if m.Trainer != nil {
		l = m.Trainer.Size()
		n += 1 + l + sovWarden(uint64(l))
	}
	if m.Zone != nil {
		l = m.Zone.Size()
		n += 1 + l + sovWarden(uint64(l))
	}
	if m.Time != nil {
		l = m.Time.Size()
		n += 1 + l + sovWarden(uint64(l))
	}
	if m.Expires != nil {
		l = m.Expires.Size()
		n += 1 + l + sovWarden(uint64(l))
	}
	return n
}

func (m *Ticket_Expiry) Size() (n int) {
	var l int
	_ = l
	if m.Encounters != 0 {
		n += 1 + sovWarden(uint64(m.Encounters))
	}
	if m.Time != 0 {
		n += 1 + sovWarden(uint64(m.Time))
	}
	return n
}

func (m *Action) Size() (n int) {
	var l int
	_ = l
	if m.Move != nil {
		n += m.Move.Size()
	}
	return n
}

func (m *Action_Attack) Size() (n int) {
	var l int
	_ = l
	l = len(m.Attack)
	n += 1 + l + sovWarden(uint64(l))
	return n
}
func (m *Action_Item) Size() (n int) {
	var l int
	_ = l
	l = len(m.Item)
	n += 1 + l + sovWarden(uint64(l))
	return n
}
func (m *Action_Switch) Size() (n int) {
	var l int
	_ = l
	if m.Switch != nil {
		l = m.Switch.Size()
		n += 1 + l + sovWarden(uint64(l))
	}
	return n
}
func (m *Action_Run) Size() (n int) {
	var l int
	_ = l
	n += 2
	return n
}
func (m *BattleMessage) Size() (n int) {
	var l int
	_ = l
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovWarden(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovWarden(uint64(m.Status))
	}
	return n
}

func (m *Zone) Size() (n int) {
	var l int
	_ = l
	if m.Region != 0 {
		n += 1 + sovWarden(uint64(m.Region))
	}
	if m.OptCode != 0 {
		n += 1 + sovWarden(uint64(m.OptCode))
	}
	return n
}

func sovWarden(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozWarden(x uint64) (n int) {
	return sovWarden(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Ticket) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Ticket{`,
		`Uid:` + fmt.Sprintf("%v", this.Uid) + `,`,
		`Trainer:` + strings.Replace(fmt.Sprintf("%v", this.Trainer), "Trainer", "Trainer", 1) + `,`,
		`Zone:` + strings.Replace(fmt.Sprintf("%v", this.Zone), "Zone", "Zone", 1) + `,`,
		`Time:` + strings.Replace(fmt.Sprintf("%v", this.Time), "Timestamp", "Timestamp", 1) + `,`,
		`Expires:` + strings.Replace(fmt.Sprintf("%v", this.Expires), "Ticket_Expiry", "Ticket_Expiry", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Ticket_Expiry) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Ticket_Expiry{`,
		`Encounters:` + fmt.Sprintf("%v", this.Encounters) + `,`,
		`Time:` + fmt.Sprintf("%v", this.Time) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Action) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Action{`,
		`Move:` + fmt.Sprintf("%v", this.Move) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Action_Attack) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Action_Attack{`,
		`Attack:` + fmt.Sprintf("%v", this.Attack) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Action_Item) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Action_Item{`,
		`Item:` + fmt.Sprintf("%v", this.Item) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Action_Switch) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Action_Switch{`,
		`Switch:` + strings.Replace(fmt.Sprintf("%v", this.Switch), "Pokemon", "Pokemon", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Action_Run) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Action_Run{`,
		`Run:` + fmt.Sprintf("%v", this.Run) + `,`,
		`}`,
	}, "")
	return s
}
func (this *BattleMessage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BattleMessage{`,
		`Msg:` + fmt.Sprintf("%v", this.Msg) + `,`,
		`Status:` + fmt.Sprintf("%v", this.Status) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Zone) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Zone{`,
		`Region:` + fmt.Sprintf("%v", this.Region) + `,`,
		`OptCode:` + fmt.Sprintf("%v", this.OptCode) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringWarden(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Ticket) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWarden
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ticket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ticket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trainer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trainer == nil {
				m.Trainer = &Trainer{}
			}
			if err := m.Trainer.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Zone == nil {
				m.Zone = &Zone{}
			}
			if err := m.Zone.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Time == nil {
				m.Time = &Timestamp{}
			}
			if err := m.Time.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expires", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Expires == nil {
				m.Expires = &Ticket_Expiry{}
			}
			if err := m.Expires.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWarden(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWarden
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ticket_Expiry) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWarden
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Expiry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Expiry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encounters", wireType)
			}
			m.Encounters = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Encounters |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Time |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWarden(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWarden
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Action) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWarden
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Action: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Action: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attack", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Move = &Action_Attack{string(data[iNdEx:postIndex])}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Item", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Move = &Action_Item{string(data[iNdEx:postIndex])}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Switch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Pokemon{}
			if err := v.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Move = &Action_Switch{v}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Run", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Move = &Action_Run{b}
		default:
			iNdEx = preIndex
			skippy, err := skipWarden(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWarden
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BattleMessage) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWarden
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BattleMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BattleMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWarden
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Status |= (BattleMessage_Status(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWarden(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWarden
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Zone) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWarden
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Zone: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Zone: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			m.Region = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Region |= (Zone_Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptCode", wireType)
			}
			m.OptCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.OptCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWarden(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthWarden
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWarden(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWarden
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWarden
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthWarden
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowWarden
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipWarden(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthWarden = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWarden   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("warden.proto", fileDescriptorWarden) }

var fileDescriptorWarden = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x4f, 0xd4, 0x4e,
	0x14, 0xef, 0xec, 0x76, 0x07, 0xf6, 0x7d, 0xbf, 0x60, 0x33, 0xe1, 0xb0, 0x6e, 0x48, 0x25, 0x25,
	0x26, 0x44, 0x63, 0x17, 0xe1, 0xa0, 0x26, 0x7a, 0xd8, 0xd5, 0x4d, 0x56, 0xc1, 0xad, 0x29, 0xab,
	0x26, 0x5c, 0x4c, 0xe9, 0x0e, 0xa5, 0x59, 0xda, 0x69, 0x3a, 0xb3, 0xb2, 0x48, 0x48, 0x8c, 0x67,
	0x63, 0x4c, 0xfc, 0x27, 0x3c, 0x7a, 0xf0, 0x8f, 0xf0, 0x48, 0xe2, 0x85, 0xa3, 0x54, 0x0f, 0x1e,
	0xf9, 0x13, 0xcc, 0x4c, 0xbb, 0x06, 0x10, 0x89, 0x97, 0xf6, 0xbd, 0x37, 0x9f, 0xcf, 0xbc, 0xcf,
	0xfb, 0xd1, 0xc2, 0xff, 0x3b, 0x5e, 0xda, 0xa7, 0xb1, 0x9d, 0xa4, 0x4c, 0x30, 0x32, 0xb3, 0x31,
	0xf4, 0x07, 0x5b, 0x23, 0x9b, 0x7b, 0x9b, 0x5e, 0x1a, 0xda, 0xf9, 0x59, 0x7d, 0x36, 0x60, 0x2c,
	0xd8, 0xa6, 0x0d, 0x2f, 0x09, 0x1b, 0x5e, 0x1c, 0x33, 0xe1, 0x89, 0x90, 0xc5, 0x3c, 0xe7, 0xd4,
	0xa7, 0x53, 0x1a, 0x84, 0x5c, 0xa4, 0xbb, 0x85, 0x3f, 0x95, 0xb0, 0x01, 0xed, 0xd3, 0x51, 0xe1,
	0x56, 0x23, 0x1e, 0xe4, 0xa6, 0xf5, 0xb9, 0x04, 0xb8, 0x17, 0xfa, 0x03, 0x2a, 0x88, 0x01, 0xe5,
	0x61, 0xd8, 0xaf, 0xa1, 0x39, 0xb4, 0x50, 0x75, 0xa5, 0x49, 0xee, 0xc0, 0x84, 0x48, 0xbd, 0x30,
	0xa6, 0x69, 0xad, 0x34, 0x87, 0x16, 0xfe, 0x5b, 0xba, 0x62, 0x9f, 0x16, 0xf3, 0x3b, 0x4d, 0x2f,
	0x87, 0xb9, 0x63, 0x3c, 0xb1, 0x41, 0x7f, 0xc5, 0x62, 0x5a, 0x2b, 0x2b, 0x5e, 0xdd, 0x3e, 0xaf,
	0x08, 0x7b, 0x9d, 0xc5, 0xd4, 0x55, 0x38, 0xb2, 0x08, 0xba, 0x08, 0x23, 0x5a, 0xd3, 0x15, 0x7e,
	0xf6, 0x0c, 0x5e, 0xea, 0xed, 0x85, 0x11, 0xe5, 0xc2, 0x8b, 0x12, 0x57, 0x21, 0xc9, 0x3d, 0x98,
	0xa0, 0xa3, 0x24, 0x4c, 0x29, 0xaf, 0x55, 0x14, 0x69, 0xfe, 0xfc, 0x24, 0x79, 0x75, 0x76, 0x5b,
	0x62, 0x77, 0xdd, 0x31, 0xa7, 0x7e, 0x17, 0x70, 0x1e, 0x22, 0x26, 0x00, 0x8d, 0x7d, 0x36, 0x8c,
	0x05, 0x4d, 0xb9, 0x2a, 0xbf, 0xe2, 0x9e, 0x88, 0x10, 0x52, 0x48, 0x93, 0x2d, 0x28, 0xe7, 0xc9,
	0xad, 0x77, 0x08, 0x70, 0xd3, 0x97, 0x2d, 0x27, 0x35, 0xc0, 0x9e, 0x10, 0x9e, 0x3f, 0xc8, 0x3b,
	0xd7, 0xd1, 0xdc, 0xc2, 0x27, 0x33, 0xa0, 0x87, 0x82, 0x46, 0x8a, 0x28, 0xe3, 0xca, 0x23, 0xb7,
	0x01, 0xf3, 0x9d, 0x50, 0xf8, 0x5b, 0x45, 0x6f, 0xcc, 0x33, 0xb2, 0xc7, 0xa3, 0x7a, 0xc2, 0x06,
	0x34, 0x62, 0xb1, 0xbc, 0x2f, 0xc7, 0x13, 0x02, 0xe5, 0x74, 0x18, 0xab, 0x16, 0x4d, 0x76, 0x34,
	0x57, 0x3a, 0x2d, 0x0c, 0x7a, 0xc4, 0x5e, 0x52, 0xeb, 0x2d, 0x82, 0xa9, 0x96, 0x27, 0xc4, 0x36,
	0x7d, 0x4c, 0x39, 0xf7, 0x02, 0x2a, 0xc7, 0x19, 0xf1, 0x60, 0x3c, 0xce, 0x88, 0x07, 0xa4, 0x05,
	0x98, 0x0b, 0x4f, 0x0c, 0xb9, 0x52, 0x34, 0xbd, 0x74, 0xed, 0xfc, 0x86, 0x9d, 0xba, 0xc6, 0x5e,
	0x53, 0x0c, 0xb7, 0x60, 0x5a, 0x57, 0x01, 0xe7, 0x11, 0x82, 0xa1, 0xe4, 0xac, 0x18, 0x1a, 0x99,
	0x04, 0xfd, 0x81, 0xd3, 0x6d, 0x1b, 0x88, 0x54, 0xa1, 0xd2, 0x76, 0x5d, 0xc7, 0x35, 0x4a, 0xd6,
	0x27, 0x04, 0xba, 0x9c, 0x2e, 0xb9, 0x05, 0x58, 0x2e, 0x09, 0x8b, 0x95, 0x90, 0xe9, 0x3f, 0x36,
	0xe8, 0xc4, 0x26, 0xd8, 0xf7, 0x59, 0x9f, 0xba, 0x05, 0x9c, 0x5c, 0x86, 0x49, 0x96, 0x88, 0x17,
	0x3e, 0xeb, 0xd3, 0xda, 0x25, 0x35, 0x93, 0x09, 0x96, 0x08, 0x09, 0xb1, 0x7a, 0xa0, 0xcb, 0xb7,
	0xcc, 0xb7, 0xd2, 0xec, 0xf6, 0x1c, 0x43, 0x93, 0xe6, 0x23, 0xa7, 0xd3, 0x73, 0x72, 0x15, 0x1d,
	0xa7, 0xdd, 0xed, 0x1a, 0x25, 0x02, 0x80, 0xd7, 0x1e, 0x76, 0xbb, 0x4e, 0xc7, 0x28, 0xcb, 0xf0,
	0xd3, 0xae, 0xf3, 0xac, 0x69, 0xe8, 0x39, 0x6f, 0xd5, 0x59, 0x33, 0x2a, 0xd2, 0x6c, 0xae, 0x3a,
	0xab, 0x4d, 0x03, 0x2f, 0x1d, 0x22, 0xc0, 0xcf, 0x95, 0x1a, 0x32, 0x82, 0x4a, 0x5b, 0xce, 0x9e,
	0xcc, 0x5e, 0xb4, 0x52, 0xf5, 0x0b, 0x4f, 0xad, 0xe5, 0x37, 0x5f, 0x7f, 0x7c, 0x28, 0xdd, 0x20,
	0xd7, 0x1b, 0xc5, 0x37, 0xd1, 0xd8, 0x2b, 0x0c, 0x7b, 0x18, 0xf6, 0xf7, 0x1b, 0x72, 0xed, 0x1b,
	0x7b, 0xf2, 0x69, 0x8f, 0x0b, 0xdd, 0x27, 0x3d, 0xa8, 0xb6, 0xc7, 0x9b, 0xf7, 0xb7, 0xec, 0xf9,
	0xde, 0xd5, 0xe7, 0xff, 0x61, 0x7a, 0x96, 0xb6, 0x80, 0x16, 0x51, 0xeb, 0xe6, 0xc1, 0x91, 0xa9,
	0x1d, 0x1e, 0x99, 0xda, 0xf1, 0x91, 0x89, 0x5e, 0x67, 0x26, 0xfa, 0x98, 0x99, 0xe8, 0x4b, 0x66,
	0xa2, 0x83, 0xcc, 0x44, 0xdf, 0x32, 0x13, 0xfd, 0xcc, 0x4c, 0xed, 0x38, 0x33, 0xd1, 0xfb, 0xef,
	0xa6, 0xb6, 0x5e, 0x4e, 0x36, 0x36, 0x37, 0xb0, 0xfa, 0x3d, 0x2c, 0xff, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x34, 0x62, 0xa9, 0x64, 0x8c, 0x04, 0x00, 0x00,
}
